In [11]:
import torch
device = 'cuda' if torch.cuda.is_available else 'cpu'
print(device)

cuda


In [1]:
import torch
text = """
Dorothy lived in Kansas with her Aunt Em and Uncle Henry. One day, a tornado swept Dorothy and her dog Toto to the magical land of Oz. 
In Oz, Dorothy met the Scarecrow who wanted a brain, the Tin Woodman who wanted a heart, and the Cowardly Lion who wanted courage. 
They traveled together to see the Wizard of Oz in the Emerald City, hoping he would grant their wishes. 
Along the way, they faced challenges, but with friendship and courage, they overcame them. 
In the end, Dorothy discovered that she had the power to return home all along, and she woke up back in Kansas, realizing that there’s no place like home.
"""
chars = sorted(list(set(text)))
string_to_int = { ch:i for i, ch in enumerate(chars) }
int_to_string = { i:ch for i, ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])
data = torch.tensor(encode(text), dtype=torch.long)
print("First 100 characters as tensor:", data[:100])
print("Vocabulary size:", len(chars))
print("Sample decoded text:", decode(data[:100].tolist()))

First 100 characters as tensor: tensor([ 0,  6, 30, 32, 30, 34, 24, 38,  1, 27, 25, 36, 21, 20,  1, 25, 29,  1,
        10, 17, 29, 33, 17, 33,  1, 37, 25, 34, 24,  1, 24, 21, 32,  1,  4, 35,
        29, 34,  1,  7, 28,  1, 17, 29, 20,  1, 15, 29, 19, 27, 21,  1,  8, 21,
        29, 32, 38,  3,  1, 12, 29, 21,  1, 20, 17, 38,  2,  1, 17,  1, 34, 30,
        32, 29, 17, 20, 30,  1, 33, 37, 21, 31, 34,  1,  6, 30, 32, 30, 34, 24,
        38,  1, 17, 29, 20,  1, 24, 21, 32,  1])
Vocabulary size: 41
Sample decoded text: 
Dorothy lived in Kansas with her Aunt Em and Uncle Henry. One day, a tornado swept Dorothy and her 


In [2]:
string_to_int = { ch:i for i, ch in enumerate(chars) }
int_to_string = { i:ch for i, ch in enumerate(chars) }
encode = lambda s: [string_to_int[c] for c in s]
decode = lambda l: ''.join([int_to_string[i] for i in l])
data = torch.tensor(encode(text), dtype = torch.long)
print(data[:100])

tensor([ 0,  6, 30, 32, 30, 34, 24, 38,  1, 27, 25, 36, 21, 20,  1, 25, 29,  1,
        10, 17, 29, 33, 17, 33,  1, 37, 25, 34, 24,  1, 24, 21, 32,  1,  4, 35,
        29, 34,  1,  7, 28,  1, 17, 29, 20,  1, 15, 29, 19, 27, 21,  1,  8, 21,
        29, 32, 38,  3,  1, 12, 29, 21,  1, 20, 17, 38,  2,  1, 17,  1, 34, 30,
        32, 29, 17, 20, 30,  1, 33, 37, 21, 31, 34,  1,  6, 30, 32, 30, 34, 24,
        38,  1, 17, 29, 20,  1, 24, 21, 32,  1])


In [3]:
randint = torch.randint(-100, 100, (9,))
randint

tensor([-59, -57, -61,  87, -85,  -1,   5, -26, -78])

In [14]:
tensor = torch.tensor([[3,3,3], [2,3,5], [1,2,3]])
tensor

tensor([[3, 3, 3],
        [2, 3, 5],
        [1, 2, 3]])

In [15]:
linspace = torch.linspace(5,10, steps=9)
linspace

tensor([ 5.0000,  5.6250,  6.2500,  6.8750,  7.5000,  8.1250,  8.7500,  9.3750,
        10.0000])

In [16]:
eye = torch.eye(5)
eye

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [18]:
tensor = torch.empty(2,3)
tensor

tensor([[0., 0., 0.],
        [0., 0., 0.]])